name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error:
      ${{ contains(fromJson('["snapshot"]'), matrix.emacs_version) }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        emacs_version:
          - '24.1'
          - '24.2'
          - '24.3'
          - '24.4'
          - '24.5'
          - '25.1'
          - '25.2'
          - '25.3'
          - '26.1'
          - '26.2'
          - '26.3'
          - '27.1'
          - '27.2'
          - 'snapshot'
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        if: ${{ contains(fromJson('["ubuntu-latest" "macos-latest"]'), matrix.os) }}
        with:
          version: ${{ matrix.emacs_version }}
      - uses: jcs090218/setup-emacs-windows@master
        if: matrix.os == 'windows-latest'
      - uses: conao3/setup-keg@master

      - run: keg install
      - run: keg run test-all
        env:
          UNDERCOVER_FORCE: true
      - uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-latest
    continue-on-error: ${{ true }}
    steps:
      - uses: actions/checkout@v1
      - uses: purcell/setup-emacs@master
        with:
          version: '27.2'
      - uses: conao3/setup-keg@master
      - run: keg lint
